version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: sdsc
      POSTGRES_PASSWORD: r2tadmiadc
      POSTGRES_DB: sdsc
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sdsc.com
      PGADMIN_DEFAULT_PASSWORD: r2tadmiadc
    ports:
      - '54321:80'
    depends_on:
      - postgres

volumes:
  pgdata:
    driver: local
